version: '3.1'

services:

  web:
    image: registry.cn-hangzhou.aliyuncs.com/catshop/catshop:prod
    volumes:
      - .:/app
    ports:
      - 8080:80
    restart: always
    environment:
      WEB_ALIAS_DOMAIN: weeshop.test
      TZ: Asia/Shanghai
      PHP_DATE_TIMEZONE: Asia/Shanghai
      WEB_DOCUMENT_ROOT: /app/web
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_HOST: host.docker.internal
      XDEBUG_REMOTE_AUTOSTART: 1
      #php.opcache.enable: 0

  db:
    image: mysql:5.7
    ports:
      - "3366:3306"
    volumes:
      - "./data/mysql/data:/var/lib/mysql"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: weeshop
